//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: System.Reflection.AssemblyTitleAttribute("")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Code generated by ScreenMaker - Internal version 7.0.8746.631")]
[assembly: System.Reflection.AssemblyCompanyAttribute("")]
[assembly: System.Reflection.AssemblyProductAttribute("")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("")]
[assembly: System.Reflection.AssemblyTrademarkAttribute("")]
[assembly: System.Reflection.AssemblyCultureAttribute("")]
[assembly: System.Reflection.AssemblyVersionAttribute("6.10.69")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("7.0.8746.631")]
[assembly: ABB.Robotics.Tps.Taf.TpsViewAttribute("Robótica UNAL", "LogoUNAL.png", "LogoUNAL.png", "TpsViewScreenMaker_1.dll", "ScreenMaker_1.MainScreen", ABB.Robotics.Tps.Taf.StartPanelLocation.Left, ABB.Robotics.Tps.Taf.TpsViewType.Static, ABB.Robotics.Tps.Taf.TpsViewStartupTypes.Manual)]


