<Project>
	<PropertyGroup>
		<MainScreenIndex>0</MainScreenIndex>
	</PropertyGroup>
	<ScreenMakerVersion>7.0</ScreenMakerVersion>
	<Type>FlexPendant</Type>
	<References />
	<Controller GUID="5e464fcb-2785-46a3-85d6-b32b75206fe1" Name="LUISA-LAPTOP" System="ControladorLuisa" />
	<AssemblyInfo>
		<Title></Title>
		<Description>Code generated by ScreenMaker - Internal version 7.0.8746.631</Description>
		<Company></Company>
		<Product></Product>
		<Copyright></Copyright>
		<Trademark></Trademark>
		<Version>6.10.69</Version>
	</AssemblyInfo>
	<TpsViewInfo>
		<Caption>Robótica UNAL</Caption>
		<MenuImageName>LogoUNAL.png</MenuImageName>
		<TaskbarImageName>LogoUNAL.png</TaskbarImageName>
		<StartPanelLocation>1</StartPanelLocation>
		<ViewType>1</ViewType>
		<StartupType>0</StartupType>
	</TpsViewInfo>
	<ApplicationVariables>
		<Variable Name="Soldar2" Value="True" ValueType="ABB.Robotics.Controllers.RapidDomain.Bool,ABB.Robotics.Controllers.PC" />
		<Variable Name="Soldar1" Value="True" ValueType="ABB.Robotics.Controllers.RapidDomain.Bool,ABB.Robotics.Controllers.PC" />
	</ApplicationVariables>
	<ItemGroup />
	<ItemGroup>
		<Compile Include=".\MainScreen.view">
			<Link>MainScreen.view</Link>
		</Compile>
		<Compile Include=".\ROBT_UNAL.view">
			<Link>ROBT_UNAL.view</Link>
		</Compile>
	</ItemGroup>
	<StartVirtualFlexPendant>False</StartVirtualFlexPendant>
	<FPSDKInfo>
		<Version>6.10.69</Version>
	</FPSDKInfo>
	<WidgetInfo />
</Project>